/**
 * Test script to mint a rat and verify the metadata flow
 * 
 * Usage:
 * npx hardhat run scripts/mint-test.ts --network base
 * 
 * This will:
 * 1. Mint a rat
 * 2. Emit RatMinted event
 * 3. Webhook catches event → calls /api/rat-mint
 * 4. API generates metadata → uploads to Blob Storage
 * 5. tokenURI points to the uploaded metadata
 */

import { ethers } from "hardhat";

async function main() {
    const RAT_NFT_ADDRESS = process.env.NEXT_PUBLIC_RAT_NFT_ADDRESS;

    if (!RAT_NFT_ADDRESS) {
        throw new Error("NEXT_PUBLIC_RAT_NFT_ADDRESS not set in .env");
    }

    console.log("Testing rat mint at:", RAT_NFT_ADDRESS);

    const [minter] = await ethers.getSigners();
    console.log("Minting to:", minter.address);

    const RatNFT = await ethers.getContractAt("RatNFT", RAT_NFT_ADDRESS);

    // Get next token ID before minting
    const nextTokenId = await RatNFT.nextTokenId();
    console.log("\nNext token ID will be:", nextTokenId.toString());

    // Mint
    console.log("\nMinting rat...");
    const tx = await RatNFT.mint(minter.address);
    console.log("Transaction sent:", tx.hash);

    const receipt = await tx.wait();
    console.log("Transaction confirmed!");

    // Find RatMinted event
    const event = receipt?.logs.find((log: any) => {
        try {
            const parsed = RatNFT.interface.parseLog({
                topics: log.topics as string[],
                data: log.data,
            });
            return parsed?.name === "RatMinted";
        } catch {
            return false;
        }
    });

    if (event) {
        const parsed = RatNFT.interface.parseLog({
            topics: event.topics as string[],
            data: event.data,
        });
        console.log("\nRatMinted event emitted:");
        console.log("  to:", parsed?.args.to);
        console.log("  tokenId:", parsed?.args.tokenId.toString());
    }

    // Get token URI
    const tokenURI = await RatNFT.tokenURI(nextTokenId);
    console.log("\nToken URI:", tokenURI);

    // Get owner balance
    const balance = await RatNFT.balanceOf(minter.address);
    console.log("Owner balance:", balance.toString());

    console.log("\n✓ Rat minted successfully!");
    console.log("\nNOTE: The metadata will be generated by the /api/rat-mint webhook.");
    console.log("Check your Vercel logs to see the metadata generation.");
    console.log("Metadata URL:", tokenURI);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });

