/**
 * Script to mint rats to specific wallets (for testing)
 * 
 * Usage:
 * npx hardhat run scripts/owner-mint-to-wallets.ts --network base
 */

import { ethers } from "hardhat";

const TEST_WALLETS = [
    "0x584cb34c3d52bf59219e4e836feaf63d4f90c830",
    "0xa41f6558A517e6aC35DeA5A453273Aa4F31CDAcD",
];

async function main() {
    const RAT_NFT_ADDRESS = process.env.NEXT_PUBLIC_RAT_NFT_ADDRESS;

    if (!RAT_NFT_ADDRESS) {
        throw new Error("NEXT_PUBLIC_RAT_NFT_ADDRESS not set in .env");
    }

    console.log("Minting rats to test wallets...");
    console.log("RatNFT Contract:", RAT_NFT_ADDRESS);
    console.log("");

    const [deployer] = await ethers.getSigners();
    console.log("Deployer:", deployer.address);
    console.log("");

    const RatNFT = await ethers.getContractAt("RatNFT", RAT_NFT_ADDRESS);

    // Mint 3 rats to each wallet
    for (const wallet of TEST_WALLETS) {
        console.log(`Minting 3 rats to ${wallet}...`);

        for (let i = 0; i < 3; i++) {
            const tx = await RatNFT.ownerMint(wallet);
            const receipt = await tx.wait();

            // Find RatMinted event
            const event = receipt?.logs.find((log: any) => {
                try {
                    const parsed = RatNFT.interface.parseLog({
                        topics: log.topics as string[],
                        data: log.data,
                    });
                    return parsed?.name === "RatMinted";
                } catch {
                    return false;
                }
            });

            if (event) {
                const parsed = RatNFT.interface.parseLog({
                    topics: event.topics as string[],
                    data: event.data,
                });
                console.log(`  ✓ Minted rat #${parsed?.args.tokenId} to ${parsed?.args.to}`);
            }
        }
        console.log("");
    }

    console.log("✓ All rats minted successfully!");
    console.log("");
    console.log("NOTE: Metadata will be generated by the /api/rat-mint webhook.");
    console.log("Make sure webhooks are configured before minting.");
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });

